import { setQuantity, collectionValue, totalOwned } from "../core/collection.js";
import { calculateOwnership } from "../core/decks.js";
import { addLocation } from "../core/locations.js";
import { $, h, money, state, catalog, cardMap, persist } from "./state.js";
import { addBuy } from "./cards.js";

export function renderCollection(){
  const rows=state.collection.map(item=>{const card=cardMap.get(item.cardId),unit=item.finish==="foil"?card?.prices?.usdFoil:item.finish==="etched"?card?.prices?.usdEtched:card?.prices?.usd;return`<tr><td>${h(item.name)}<br><small>${h(item.setCode)} #${h(item.collectorNumber)}</small></td><td><input class="field qty" data-id="${h(item.id)}" type="number" min="0" value="${item.quantity}"></td><td><select class="field condition" data-id="${h(item.id)}">${["NM","LP","MP","HP","DMG"].map(x=>`<option ${x===item.condition?"selected":""}>${x}</option>`).join("")}</select></td><td><select class="field finish" data-id="${h(item.id)}">${["nonfoil","foil","etched"].map(x=>`<option ${x===item.finish?"selected":""}>${x}</option>`).join("")}</select></td><td><input class="field language" data-id="${h(item.id)}" value="${h(item.language)}"></td><td><select class="field location" data-id="${h(item.id)}">${state.locations.map(x=>`<option ${x===item.location?"selected":""}>${h(x)}</option>`).join("")}</select></td><td>${money(unit)}</td><td>${unit==null?"Unknown":money(unit*item.quantity)}</td><td><button class="remove" data-id="${h(item.id)}">Remove</button></td></tr>`;}).join("");
  $("#collection").innerHTML=`<div class="panel"><h2>Collection</h2><div class="metric-grid"><div class="metric"><span>Owned copies</span><strong>${totalOwned(state.collection)}</strong></div><div class="metric"><span>Estimated value</span><strong>${money(collectionValue(state.collection,cardMap))}</strong></div><div class="metric"><span>Stacks</span><strong>${state.collection.length}</strong></div></div><div class="split"><label>New location<input id="newLocation" class="field" placeholder="Binder, box, shelf..."></label><p><button id="addLocation">Add location</button></p></div></div><div class="panel table-wrap">${rows?`<table><thead><tr><th>Printing</th><th>Qty</th><th>Condition</th><th>Finish</th><th>Lang</th><th>Location</th><th>Unit</th><th>Value</th><th></th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">No cards saved yet.</div>'}</div>`;
  $("#addLocation").onclick=()=>{state.locations=addLocation(state.locations,$("#newLocation").value);persist();renderCollection();};
  document.querySelectorAll("#collection .qty").forEach(x=>x.onchange=()=>{const i=state.collection.findIndex(v=>v.id===x.dataset.id);if(i>=0)state.collection[i]=setQuantity(state.collection[i],x.value);persist();renderCollection();});
  for(const key of["condition","finish","language","location"])document.querySelectorAll(`#collection .${key}`).forEach(x=>x.onchange=()=>{const i=state.collection.findIndex(v=>v.id===x.dataset.id);if(i>=0)state.collection[i]={...state.collection[i],[key]:key==="language"?(x.value.trim()||"en"):x.value};persist();if(key==="finish")renderCollection();});
  document.querySelectorAll("#collection .remove").forEach(x=>x.onclick=()=>{state.collection=state.collection.filter(v=>v.id!==x.dataset.id);persist();renderCollection();});
}

export function renderSets(){
  const groups=new Map();for(const card of catalog){const g=groups.get(card.setCode)||{name:card.setName,cards:[]};g.cards.push(card);groups.set(card.setCode,g);}
  const draw=query=>{query=query.toLowerCase();const list=[...groups.entries()].filter(([code,g])=>!query||code.toLowerCase().includes(query)||g.name.toLowerCase().includes(query)).slice(0,250);$("#setResults").innerHTML=list.map(([code,g])=>{const owned=g.cards.filter(card=>state.collection.some(i=>i.cardId===card.id&&i.quantity>0)).length;return`<article class="panel"><h3>${h(code)} · ${h(g.name)}</h3><div class="metric"><span>Completion</span><strong>${owned}/${g.cards.length}</strong></div><p>${Math.round(owned/g.cards.length*100)||0}% complete</p><button data-set="${h(code)}">Add missing to Buy List</button></article>`;}).join("");$("#setResults").querySelectorAll("[data-set]").forEach(button=>button.onclick=()=>{for(const card of groups.get(button.dataset.set).cards)if(!state.collection.some(i=>i.cardId===card.id&&i.quantity>0))addBuy(card,Math.max(0,1-(state.buyList.find(x=>x.cardId===card.id)?.quantity||0)));renderBuy();});};
  $("#sets").innerHTML='<div class="panel"><h2>Sets</h2><input id="setQuery" class="field" placeholder="Search loaded/cached set name or code"></div><div id="setResults" class="cards"></div>';$("#setQuery").oninput=e=>draw(e.target.value);draw("");
}

export function renderDecks(){
  const deck=state.decks[0],ownership=calculateOwnership(deck.entries,state.collection),missing=ownership.reduce((n,x)=>n+x.missing,0);
  $("#decks").innerHTML=`<div class="panel"><h2>Decks</h2><div class="split"><label>Name<input id="deckName" class="field" value="${h(deck.name)}"></label><label>Format<select id="deckFormat" class="field">${["commander","standard","modern","pioneer","legacy","vintage","pauper"].map(x=>`<option ${x===deck.format?"selected":""}>${x}</option>`).join("")}</select></label></div></div><div class="panel"><div class="card-title-row"><h3>Ownership</h3><button id="buyMissing" ${missing?"":"disabled"}>Buy all missing (${missing})</button></div>${ownership.length?`<div class="table-wrap"><table><thead><tr><th>Card</th><th>Need</th><th>Exact</th><th>Alternate</th><th>Missing</th></tr></thead><tbody>${ownership.map(x=>`<tr><td>${h(x.name)}</td><td>${x.quantity}</td><td>${x.exactOwned}</td><td>${x.alternateOwned}</td><td class="${x.missing?"danger":"success"}">${x.missing}</td></tr>`).join("")}</tbody></table></div>`:'<div class="empty">Add cards from Search or import a deck list.</div>'}</div>`;
  $("#deckName").onchange=e=>{deck.name=e.target.value;persist();};$("#deckFormat").onchange=e=>{deck.format=e.target.value;persist();};$("#buyMissing").onclick=()=>{for(const x of ownership.filter(x=>x.missing))addBuy(cardMap.get(x.cardId),x.missing);renderBuy();};
}

export function renderBuy(){const total=state.buyList.reduce((sum,x)=>sum+(cardMap.get(x.cardId)?.prices?.usd??0)*x.quantity,0);$("#buy").innerHTML=`<div class="panel"><h2>Buy Lists / Wishlist</h2><div class="metric"><span>Estimated retail</span><strong>${money(total)}</strong></div></div><div class="panel table-wrap">${state.buyList.length?`<table><thead><tr><th>Card</th><th>Qty</th><th>Finish</th><th>Current</th><th>Target</th><th>Priority</th></tr></thead><tbody>${state.buyList.map(x=>`<tr><td>${h(x.name)}</td><td>${x.quantity}</td><td>${h(x.finish)}</td><td>${money(cardMap.get(x.cardId)?.prices?.usd)}</td><td>${x.targetPrice==null?"—":money(x.targetPrice)}</td><td>${h(x.priority)}</td></tr>`).join("")}</tbody></table>`:'<div class="empty">No cards on a buy list.</div>'}</div>`;}
export function renderPricing(){const known=catalog.filter(c=>c.prices?.usd!=null).length;$("#pricing").innerHTML=`<div class="panel"><h2>Pricing / Value</h2><p class="muted">Missing provider prices remain unknown, never $0. Price data is an estimate, not a guaranteed transaction value.</p></div><div class="metric-grid"><div class="metric"><span>Collection</span><strong>${money(collectionValue(state.collection,cardMap))}</strong></div><div class="metric"><span>USD prices known</span><strong>${known}/${catalog.length}</strong></div><div class="metric"><span>Buy list</span><strong>${money(state.buyList.reduce((s,x)=>s+(cardMap.get(x.cardId)?.prices?.usd??0)*x.quantity,0))}</strong></div></div>`;}
